import mp4 from "../src/components/Images/icons/mp4.png";
import a from "../src/components/Images/icons/mp4.png";
import vehicle from "../src/components/Images/icons/van.png";
import loading from "../src/components/Images/icons/loading.png";
import Unloading from "../src/components/Images/icons/unloading.png";
import video1 from "../src/components/Videos/video1.mp4";
import video2 from "../src/components/Videos/video2.mp4";
import camera from "../src/components/Images/icons/anpr.png";

export const alerts = [
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
  {
    name: "Shubham",
    Age: 22,
    Phone: 1234567899,
    UName: "Shubham",
    img: a,
  },
];

export const anpr = [
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video2,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
  {
    warehouse_location: "Abc",
    camera_location: 22,
    vehicle_number: 1234567899,
    entry: "Abc",
    exit: "12",
    duration: "10",
    img: mp4,
    video: video1,
  },
];

export const card_details = [
  {
    card_name: "Vehicle Counter",
    count: "62",
    img: vehicle,
  },
  {
    card_name: "Loding Vehicle Counter",
    count: "420",
    img: loading,
  },
  {
    card_name: "Unloading Vehicle Counter",
    count: "164",
    img: Unloading,
  },
  {
    card_name: "Number Plate Recognized",
    count: "565",
    img: vehicle,
  },
  {
    card_name: "Number Plate Recognized",
    count: "62",
    img: vehicle,
  },
  {
    card_name: "Total Cameras Connected",
    count: "658",
    img: camera,
  },
];

export const videos = [
  {
    vid: video1,
  },
  {
    vid: video2,
  },
];

export const progressBar = [
  {
    name: "Mask",
    percent: "65%",
  },
  {
    name: "Palette & Forklift",
    percent: "96%",
  },
  {
    name: "Social Distancing",
    percent: "88%",
  },
  {
    name: "Loitering",
    percent: "96%",
  },
];
