import alert_png from "../components/Images/icons/mp4.png";

export const alerts = [
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
    {
      priority: "High",
      location: "Mumbai",
      camera_location: "Corridor",
      camera_name: "Baygate1",
      alert: "loitering",
      timestamp: "27-08-2021  08:44:52",
      assigned_to: "xyz",
      status: "open",
      img: alert_png,
    },
  ];