import alert_png from "../components/Images/icons/jpg.png";
import one from '../components/Images/1.png'
import two from '../components/Images/2.png'
import three from '../components/Images/3.png'
import four from '../components/Images/4.png'
import five from '../components/Images/5.png'
import six from '../components/Images/6.png'
import seven from '../components/Images/7.png'

export const alerts = [
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: one
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: two
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: three
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: four
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: five
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: six
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: seven
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: one
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: two
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: three
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: four
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: five
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: six
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallet Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: seven
  },
]

export const sec_analysis = [
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
    img_url: alert_png
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  }
];
