import alert_png from "../components/Images/icons/jpg.png";
import one from "../components/Images/Alerts/1.png";
import two from "../components/Images/Alerts/2.png";
import three from "../components/Images/Alerts/3.png";
import four from "../components/Images/Alerts/4.png";
import five from "../components/Images/Alerts/5.png";
import six from "../components/Images/Alerts/6.png";
import seven from "../components/Images/Alerts/7.png";
import fk_11 from "../components/Images/Alerts/11-fk.png";
import pl_11 from "../components/Images/Alerts/11-pl.png";
import pl_13 from "../components/Images/Alerts/13_pl.png";
import fk_15 from "../components/Images/Alerts/15_fk.png";
import pl_15 from "../components/Images/Alerts/15_pl.png";
import fk_24 from "../components/Images/Alerts/24_fk.png";
import fk1_24 from "../components/Images/Alerts/24_fk1.png";
import pl_24 from "../components/Images/Alerts/24_pl.png";
import pl1_24 from "../components/Images/Alerts/24_pl1.png";

export const alerts = [
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "11-08-2021 10:19:13",
    img: alert_png,
    img_url: fk_11,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "11-08-2021 10:19:27",
    img: alert_png,
    img_url: pl_11,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "13-08-2021 03:42:45",
    img: alert_png,
    img_url: pl_13,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "15-08-2021 11:51:46",
    img: alert_png,
    img_url: fk_15,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "15-08-2021 12:09:19",
    img: alert_png,
    img_url: pl_15,
  },

  // ------------------------------------------------------------------------------
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  06:34:09",
    img: alert_png,
    img_url: two,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  06:37:49",
    img: alert_png,
    img_url: five,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:38:28",
    img: alert_png,
    img_url: one,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  07:13:00",
    img: alert_png,
    img_url: six,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  07:14:24",
    img: alert_png,
    img_url: four,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: two,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  07:25:17",
    img: alert_png,
    img_url: three,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: one,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: one,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: one,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: one,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "23-08-2021  06:40:17",
    img: alert_png,
    img_url: seven,
  },

  // ------------------------------------------------------------------------------

  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "24-08-2021 9:01:53",
    img: alert_png,
    img_url: fk_24,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "24-08-2021  09:30:17",
    img: alert_png,
    img_url: pl_24,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Forklift Detected",
    timestamp: "24-08-2021  10:08:17",
    img: alert_png,
    img_url: fk1_24,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Baygate2",
    camera_name: "Cam_9",
    alert: "Pallete Detected",
    timestamp: "24-08-2021  10:08:17",
    img: alert_png,
    img_url: pl1_24,
  },
];

// --------------------------------------------------------------------------

export const actDuration = [
  {
    srNo: 1,
    date: "11/08/2021",
    type: "Loading",
    startTime: "10:00:00",
    endTime: "10:25:00",
    worker: 7,
    location: "Mumbai",
    actTime: "25 mins",
  },
  {
    srNo: 2,
    date: "15/08/2021",
    type: "Loading",
    startTime: "11:42:00",
    endTime: "11:54:00",
    worker: 4,
    location: "Mumbai",
    actTime: "12 mins",
  },
  {
    srNo: 3,
    date: "24/08/2021",
    type: "Unloading",
    startTime: "08:56:00",
    endTime: "09:11:00",
    worker: 4,
    location: "Mumbai",
    actTime: "15 mins",
  },
  {
    srNo: 4,
    date: "24/08/2021",
    type: "Loading",
    startTime: "09:48:00",
    endTime: "10:07:00",
    worker: 5,
    location: "Mumbai",
    actTime: "21 mins",
  },
];

// -----------------------------------------------------------------------------

export const sec_analysis = [
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
    img_url: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
  {
    priority: "High",
    location: "Mumbai",
    camera_location: "Corridor",
    camera_name: "Baygate1",
    alert: "loitering",
    timestamp: "27-08-2021  08:44:52",
    assigned_to: "xyz",
    status: "open",
    cam_tampering: "true",
    alerts_detected: "false",
    accuarcy: "100",
    img: alert_png,
  },
];
