import mp4 from "../components/Images/icons/mp4.png";
import video1 from "../components/Videos/video1.mp4";
import video2 from "../components/Videos/video2.mp4";
import alert_png from "../components/Images/icons/jpg.png";

function importAll(r) {
  let images = {};
  r.keys().map((item, index) => {
    images[item.replace("./", "")] = r(item);
  });
  console.log(images);
  return images;
}

const images = importAll(
  require.context("../components/Images/Anpr", false, /\.(png|jpe?g)$/)
);

export const anpr_data = [
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh03ar2435".toUpperCase(),
    entry: "2021-08-19 08:44:52",
    exit: "-",
    veh_type: "Van",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["08-44-52.849455.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh47x4124".toUpperCase(),
    entry: "2021-08-19 09:44:56",
    exit: "-",
    veh_type: "Van",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-44-56.762890.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "hh47y2981".toUpperCase(),
    entry: "2021-08-19 09:45:27",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-45-27.101053.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh10bf1747".toUpperCase(),
    entry: "2021-08-19 09:45:34",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-45-34.083128.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh4hm3053".toUpperCase(),
    entry: "2021-08-19 09:45:44",
    exit: "-",
    veh_type: "Big Truck",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-45-44.781114.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh44iq3053".toUpperCase(),
    entry: "2021-08-19 09:45:47",
    exit: "-",
    veh_type: "Big Truck",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-45-47.199411.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh01lf1650".toUpperCase(),
    entry: "2021-08-19 09:46:05",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-46-05.710903.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh01gv1869".toUpperCase(),
    entry: "2021-08-19 09:46:07",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-46-07.006331.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh04ge7821".toUpperCase(),
    entry: "2021-08-19 09:46:43",
    exit: "-",
    veh_type: "Van",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-46-43.552307.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh02ecq102".toUpperCase(),
    entry: "2021-08-19 09:53:52",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["09-53-52.793178.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh04gr7322".toUpperCase(),
    entry: "2021-08-19 10:24:08",
    exit: "-",
    veh_type: "Van",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-24-08.062299.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh43f8763".toUpperCase(),
    entry: "2021-08-19 10:24:16",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-24-16.185000.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh42y2381".toUpperCase(),
    entry: "2021-08-19 10:25:14",
    exit: "-",
    veh_type: "Unknown",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-25-14.644265.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh462302".toUpperCase(),
    entry: "2021-08-19 10:25:29",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-25-29.239350.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh01cw1434".toUpperCase(),
    entry: "2021-08-19 10:25:41",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-25-41.879138.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh01wd3053".toUpperCase(),
    entry: "2021-08-19 10:25:50",
    exit: "-",
    veh_type: "Big truck",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-25-50.990025.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "wh10u21747".toUpperCase(),
    entry: "2021-08-19 10:26:11",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-26-11.280045.jpg"]["default"],
  },
  {
    warehouse_location: "Mumbai",
    camera_location: "Main Gate",
    vehicle_number: "mh43ad5010".toUpperCase(),
    entry: "2021-08-19 10:26:20",
    exit: "-",
    veh_type: "Sedan",
    direction: "In",
    duration: "-",
    img: alert_png,
    img_url: images["10-26-20.786257.jpg"]["default"],
  },
];
